### ISSUE TITLE
Error in ``Fluid.FMI.BaseClasses.X_w_toX``

### ISSUE THREAD

**Issue by jmoeckel** [ibpsa/modelica#675] opened 2017-03-09 08:05 UTC
Applying Dymolas (2017 FD01) ``checkModel()`` in non-pedantic mode to ``Fluid.FMI.BaseClasses.X_w_toX`` throws following error:

`````
Size mismathc in equation:
X = cat(1, {X_w_internal}, {1-X_w_internal});

**Comment by mwetter** [comment] 2017-03-10 05:12
@jmoeckel : The error is caused because `Medium` is not assigned. This works:
```modelica
Advanced.PedanticModelica:=true;
checkModel("Annex60.Fluid.FMI.BaseClasses.X_w_toX(redeclare package Medium = Annex60.Media.Air)");
```
I will close the issue. Please reopen if you disagree and provide a full log that we can reproduce.

**Comment by thorade** [comment] 2017-03-10 08:49
We could, just to make Dymola happy, use the following:
```modelica
block X_w_toX "Conversion from Xi to X"
  extends Modelica.Blocks.Icons.Block;

  replaceable package Medium =
      BuildingSystems.Media.Air constrainedby 
    Modelica.Media.Interfaces.PartialMedium "Medium model within the source"
     annotation (choicesAllMatching=true);
```

**Comment by mwetter** [comment] 2017-03-13 22:45
@thorade We should not use default medium assignments as then it will be harder to spot situations where a medium is not propagated. Could you constrain it to a partial condensing media, or to a media with nXi > 0?

**Comment by thorade** [comment] 2017-03-14 08:31
Air extends from `Modelica.Media.Interfaces.PartialCondensingGases` but using that as constrianing type does not remove the error message. Creating a new partial medium would work, but having too many extends is also confusing. 
The following removes the error message, not sure if it has any disadvantages?
```modelica
block X_w_toX "Conversion from Xi to X"
  extends Modelica.Blocks.Icons.Block;

  replaceable package Medium =
      Modelica.Media.Interfaces.PartialCondensingGases (
     final substanceNames={"water", "air"}) "Medium model within the source"
     annotation (choicesAllMatching=true);
```

**Comment by mwetter** [comment] 2017-03-17 23:48
@thorade : I would not hardwire `substanceNames`. Would https://github.com/iea-annex60/modelica-annex60/commit/3c874e8c24dce9855672d82b0bc50f4d4da61432 work?

**Comment by thorade** [comment] 2017-03-20 09:14
Yes, that looks good. 
Dymolas check does not report any errors or warnigns for Fluid.FMI (both in pedantic and non-pedantic mode).

**Closed** 2017-03-21 13:57 UTC
